#!/usr/bin/env bash
# Manages PID file and signals

PIDFILE="/var/run/myscript.pid"

echo $$ > "$PIDFILE"

trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT

trap "rm -f $PIDFILE; exit" SIGQUIT SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
